name: "Setup Environment"
description: "Sets up Flutter and Node.js for testing environments"
runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install dependencies
      run: dart pub get
      shell: bash
