name: dateutil
description: Platform-integrated timezone library for Dart and Flutter.
version: 0.1.0
repository: https://github.com/dickermoshe/dateutil

environment:
  sdk: ^3.6.1

dependencies:
  b: ^0.2.0
  collection: ^1.19.1
  embed_annotation: ^1.2.1
  equatable: ^2.0.7
  ffi: ^2.1.3
  jni: ^0.14.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  archive: ^4.0.2
  build_runner: ^2.4.14
  embed: ^1.4.0
  ffigen: ^16.1.0
  jnigen: ^0.14.0
  lints: ^5.0.0
  melos: ^6.3.2
  test: ^1.24.0
dependency_overrides:
  build_resolvers:
    git:
      url: https://github.com/dickermoshe/build.git
      ref: master
      path: build_resolvers
