name: dateutil
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

dependencies:
  win32: ^5.10.1
  ffi: ^2.1.3
  win32_registry: ^2.0.1
dev_dependencies:
  b: ^0.2.0
  http: ^1.3.0
  lints: ^5.0.0
  melos: ^6.3.2
  path: ^1.9.1
  test: ^1.24.0
