name: dateutil
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

dependencies:
  b: ^0.2.0
  collection: ^1.19.1
  embed_annotation: ^1.2.1
  equatable: ^2.0.7
  ffi: ^2.1.3
  jni: ^0.14.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.14
  embed: ^1.4.0
  ffigen: ^16.1.0
  jnigen: ^0.14.0
  lints: ^5.0.0
  melos: ^6.3.2
  test: ^1.24.0
