name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11.0.26+4"
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Install CMake
        uses: ssrobins/install-cmake@v1
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
      - name: Install dependencies
        run: dart pub get
      - name: Test
        run: dart test
