name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-universal:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set Up Environment
        uses: ./.github/actions/setup
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11.0.26+4"
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.16.x"
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
      - name: Prepare Project
        run: dart run tool/prepare.dart
      - name: Test Java
        run: dart test test/universal_test.dart --fail-fast
