name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set Up Environment
        uses: ./.github/actions/setup
      - name: Prepare Project
        run: dart run tool/prepare.dart --skip-java --tz=2024a
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Test Web
        run: dart test test/web_test.dart --platform chrome --fail-fast

  test-java:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set Up Environment
        uses: ./.github/actions/setup
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11.0.26+4"
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.16.x"
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
      - name: Prepare Project
        run: dart run tool/prepare.dart
      - name: Test Java
        run: dart test test/java_test.dart --fail-fast

  test-mac:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set Up Environment
        uses: ./.github/actions/setup
      - name: Prepare Project
        run: dart run tool/prepare.dart --skip-java --tz=2022a
      - name: Print Timezone version
        run: cat /usr/share/zoneinfo/+VERSION
      - name: Test Mac
        run: dart test test/foundation_test.dart --fail-fast
